spring.application.name=demo
app.notifications.emailsender=ventas@tienda.com

# application.properties para conexion con base de datos mysql
# DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=mysql123

# ddl-auto = update, alinea la base de datos con la estrutura de la entidad
spring.jpa.hibernate.ddl-auto=update

# sho-sql = true, muestra la respuesta sql. Es false por defecto.
spring.jpa.show-sql=true
